### ISSUE TITLE
Clone not working

### ISSUE THREAD

**Issue by dayanandsaraswati** [astoilkov/jsblocks-shopping-example#1]
Hi,
I have tried cloning this Repo and running it on my local. To help you understand better, I am familiar with JS, nodeJS and git.
Steps: After clone when I type npm intsall it gives error in the installation part. Also the index.html inside app is giving error. I hope you consider to see the code once.

**Comment by astoilkov** [comment]
Have you successfully fixed the problem? Did you find any problem?

**Comment by dayanandsaraswati** [comment]
Need a lot of info. Would be helpful if I get your gmail id.

**Comment by astoilkov** [comment]
Yeah. Of course.

antonio.stoilkov@gmail.com
