### ISSUE TITLE
issue with images

### ISSUE THREAD

**Issue by frh3ddy** [astoilkov/jsblocks-shopping-example#2]
I notice that the images don't load when I click on a product and while in the product page I click on any link from the side nav and then go back to the home page. do you know what could be the problem? I try using safari and chrome and I have the same result in both.
![screen shot 2015-04-29 at 7 32 48 am](https://cloud.githubusercontent.com/assets/7991939/7390052/f9e2e496-ee41-11e4-8663-1b754a5bbc1e.png)

**Comment by astoilkov** [comment]
I have fixed the problem. The issue was the `src` to the image was relative and not based on the root of the application.

Before:

``` html
<img src="images/products/{{image}}-small.jpg">
```

Now:

> Note the / at the begging of the `src`.
> 
> ``` html
> <img src="/images/products/{{image}}-small.jpg">
> ```
