### ISSUE TITLE
Sidebar doesn't load on second page request

### ISSUE THREAD

**Issue by clarkeadg** [astoilkov/jsblocks-shopping-example#6]
If I go to a page without the sidebar and then navigate to a page with the sidebar, it renders as this

[object External]

Steps:
- run project and go to /news as first page loaded
- click on home link on nav and go to /

Results:
Sidebar renders as [object External]

**Comment by clarkeadg** [comment]
![6](https://cloud.githubusercontent.com/assets/1672257/7930215/415c646c-08bb-11e5-860a-8fadbce0e056.png)

**Comment by astoilkov** [comment]
I will take a look into this.

**Comment by Kanaye** [comment]
Stumbled accross this while testing astoilkov/jsblocks#109 against this app as sugested.
Things I found out:
- Appears in Firefox (maybe other browsers but definitly not chrome) when the `template()`-data-query is rendered client side.
- It renders correctly when inserting a string and not a reference to the object e.g. :

``` html
<!-- results in [object External]: -->
<div data-query="template(sidebar, Sidebar)"></div>

<!-- just  works: -->
<div data-query="template('sidebar', Sidebar)"></div>
```

That _could_ be a jsblocks issue but I'm not sure yet. I'll look into this after I'm done with testing the PR.

**Comment by Kanaye** [comment]
but using a string in `template()` data-query seems to be derpy when rendered server-side.
From the example above the content would be just `sidebar` but when rendered as reference it renders correctly.
Btw. all I comment here is tested with v0.3.4 and not my PR.

**Comment by Kanaye** [comment]
Okay the issue of the `[object External]` that occurs in firefox is one of the harder edge cases.
Let me explain:
when jsblocks finds a  data-query it starts parsing it and executes the parameters in a function which results in something like that:
data-query:`template(templateId)`

``` javascript
function (c) {
  with(c) {
     with ($this) {
       return templateId;
    } 
  }
}
```

when this function gets executet it gets the current context as the parameter.
Blocks uses the behaviour of browsers that element-ids get attached to the `window` element as the  context (c) has no ``templateId` it will return the value of `window.templateId`.
In Firefox the property `sidebar` is [already used](https://developer.mozilla.org/de/docs/Web/API/Window/sidebar) and will not get overwritten by the script with the id `sidebar`.
Firefox `window.sidebar` property will return '[object External]' when it get's converted to a string.

I think we should change the behaivor as it will fail with all properties attached to the `window` object.

[Edit: typos and words that shouldn't be there. Whoops]
