### ISSUE TITLE
Application start problem

### ISSUE THREAD

**Issue by kokujin** [astoilkov/jsblocks-shopping-example#8]
Can some one confirm that the app doe not work directly?

node: 0.12, Ubuntu 14.04

**Comment by astoilkov** [comment]
Did you run `npm install`? And if you did what error is being thrown?

**Comment by kokujin** [comment]
I did run npm install, strangely, there were no errors

**Comment by Kanaye** [comment]
Hi @kokujin!
I'm closing this right now because it's old and I can't reproduce it.
If you still have that issue (and you are still interested in finding and fixing it)
feel free to reopen it.

Have a nice day and happy coding.
